### ISSUE TITLE
Using fixture_file_upload with rspec-rails

### ISSUE THREAD

**Issue by egiurleo** [rspec/rspec-rails#2439]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.2
Rails version: 6.1.0
RSpec version: 3.10.1 (rspec-core) and 4.0.2 (rspec-rails)

## Observed behaviour

Hello! I am trying to upgrade my app to Rails 6.1 from 6.0.3.4, and I'm encountering an error when using the `fixture_file_upload` method. When I call this method, the following exception is raised:

```
     NoMethodError:
       undefined method `file_fixture_path' for RSpec::Rails::FixtureFileUploadSupport::RailsFixtureFileWrapper:Class
       Did you mean?  fixture_path
```

It seems that `ActionPack` has changed the implementation of the `fixture_file_upload` and expects there to be a `file_fixture_path` method on the `RailsFixtureFileWrapper` class.

## Expected behaviour

I expect this method to upload the file without raising any exceptions.

## Can you provide an example app?

You can see my example app with a failing test here: [https://github.com/egiurleo/fixture-file-upload-test/blob/main/spec/fixture_file_upload_spec.rb](https://github.com/egiurleo/fixture-file-upload-test/blob/main/spec/fixture_file_upload_spec.rb)

For the test, I have a pdf file in the `spec/fixtures` folder. I am trying to call the `fixture_file_upload` method with the name of that file, and the test raises the exception I described earlier.

## Notes

* I may just be using this method wrong, but I can't find any documentation that explains how to set `file_fixture_path` in this context so any guidance would be appreciated.
* The actual change was in `ActionPack` ([`lib/action_dispatch/testing/test_process.rb`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/test_process.rb#L19)).
* Thank you for your time!

**Comment by pirj** [comment]
Thanks for reporting. We're actively working on `rspec-rails` 4.1, you can access it by pointing to a branch:
```ruby
# Gemfile
gem 'rspec-rails', github: 'rspec/rspec-rails', branch: 'rails-6-1-dev'
```

The fix [is included there](https://github.com/rspec/rspec-rails/pull/2398/files#diff-8b39d8608fe8b5320cf54aa200491ff780511c118ec4653a41a57ff08091c1f4R9).

Sorry for the inconvenience.

Please feel free to report back if it still doesn't work for you.

**Comment by egiurleo** [comment]
Thank you so much for letting me know!

**Comment by KyleRAnderson** [comment]
As a temporary workaround for this, rather than fiddling with my Gemfile and making sure I had all the dependencies, I just defined my own `fixture_file_upload` method after looking at the [source code](https://api.rubyonrails.org/classes/ActionDispatch/TestProcess/FixtureFile.html#method-i-fixture_file_upload) for that method:
```ruby
def fixture_file_upload(path, mime_type)
  Rack::Test::UploadedFile.new(Pathname.new(file_fixture_path).join(path), mime_type, false)
end
```
