### ISSUE TITLE
Controller macros no longer work after upgrading from 2.14.1 to 3.2.1

### ISSUE THREAD

**Issue by neilhoff** [rspec/rspec-rails#1351]
I followed this [tutorial](https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-%28and-RSpec%29) to create a controller macro.  This worked perfect when using rspec-rails version 2.14.1.  I decided to do a `bundle update` which updated rspec-rails to 3.2.1 and now I get this error when running the specs:

    /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:635:in `method_missing': undefined local variable or method `login_admin' for RSpec::ExampleGroups::PostsController::Authentication:Class (NameError)
	from /vagrant/speech-tastic/spec/controllers/posts_controller_spec.rb:31:in `block (2 levels) in <top (required)>'
	from /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `module_exec'
	from /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `subclass'
	from /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:253:in `block in define_example_group_method'

Here are the relevant files:

- [spec_helper.rb](https://github.com/neilhoff/speech-tastic/blob/master/spec/spec_helper.rb)
- [controller_macros.rb](https://github.com/neilhoff/speech-tastic/blob/master/spec/support/controller_macros.rb)
- [posts_controller_spec.rb](https://github.com/neilhoff/speech-tastic/blob/master/spec/controllers/posts_controller_spec.rb)
- [Gemfile](https://github.com/neilhoff/speech-tastic/blob/master/Gemfile)

Any ideas?

**Comment by cupakromer** [comment]
Looks like you may need to turn on the new setting to infer spec type from file location: https://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/upgrade#file-type-inference-disabled

I hope the upgrade wasn't painful for you :blue_heart: and you were able to use [`transpec`](http://yujinakayama.me/transpec/) to automate most of it.

**Comment by myronmarston** [comment]
Alternately, you can tag the example group with explicit `:type` metadata:

``` ruby
describe PostsController, :type => :controller do
end
```
