### ISSUE TITLE
RSpec 4.1 breaks on Rails 4.2

### ISSUE THREAD

**Issue by tagliala** [rspec/rspec-rails#2477]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.4.10
Rails version: 4.2.11.3
RSpec version: 4.1.0

## Observed behaviour

RSpec 4.1 does not work start on Rails 4.2.11.3, while 4.0 does

```
     Failure/Error: example.run
     
     NameError:
       undefined local variable or method `use_transactional_tests' for #<RSpec::ExampleGroups::Welcome::Index:0x00007fcb64cdbf40>
       Did you mean?  use_transactional_fixtures
```

Tracked down with `git bisect` down to 073daad07027d7fb53a3f7ac3b06a0dd4af498da

## Expected behaviour

Keeps working with Rails 4.1 or `gemspec` specifies `>= 5.0` to prevent update to 4.1

https://github.com/rspec/rspec-rails/blob/main/rspec-rails.gemspec#L36

## Can you provide an example app?

Travis CI failure: https://travis-ci.org/github/diowa/ruby2-rails4-bootstrap-heroku/builds/761888443

**Comment by JonRowe** [comment]
:wave: RSpec-Rails 4.x maintains a soft support for Rails 4.2, but we don't actively maintain it, if you'd like to tackle this in a PR please do and I'll release it as a bugfix.

**Comment by yo-it-engineer** [comment]
Hi. We just encountered the same problem too. For the time being we also fixed rspec-rails version to 4.0.1.

**Comment by yo-it-engineer** [comment]
@pirj I'm not sure if I can explain it well, but when our Rails 4.1 system run rspec, this line caused `method not found` error.

```
NameError:
       undefined local variable or method `use_transactional_tests' for #<RSpec::ExampleGroups::Anonymous:0x000055eac3f36e08>
```

https://github.com/rspec/rspec-rails/blob/v4.1.1/lib/rspec/rails/fixture_support.rb#L16

the `use_transactional_tests ` method is not exist in Rails 4.1 I guess. I think it was introduced since Rails 5.x .

I try to tweak around and this is the way I was able to get rid of the error:
![image](https://user-images.githubusercontent.com/10822260/110602004-e330ca80-81c8-11eb-9c1c-a83f8edee6ee.png)

**Comment by tagliala** [comment]
Hi,

I've tracked down the issue to 073daad

If you can live with a try, I have a fix at tagliala/rspec-rails@12872f98c235d0c33e347d825888f8a372fbf7ab

**Comment by pirj** [comment]
Nice research, @tagliala ! 👏 

WDYT of mimicking Rails 4.2's behaviour and doing it like it does? https://github.com/rails/rails/blob/0ecaaf76d1b79cf2717cdac754e55b4114ad6599/activerecord/lib/active_record/fixtures.rb#L922
Since 5.0 this method has changed to https://github.com/rails/rails/blob/ac6aa32f7cf66264ba87eabed7c042bb60bcf3a2/activerecord/lib/active_record/fixtures.rb#L958
I'd suggest defining this method inside a `if ::Rails::VERSION::STRING > '5'` conditional.

**Comment by JonRowe** [comment]
Closed by #2480

**Comment by JonRowe** [comment]
A fix for this will be released later today as 4.1.2. 

(Please note future travellers, this does not mean we are supporting Rails 4.2 on this series of RSpec, this was an exception to the rule 😃 )
