### ISSUE TITLE
Undefined method #render_views? after update to 3.6.0

### ISSUE THREAD

**Issue by phantomwhale** [rspec/rspec-rails#1825]
I recent upgraded my app from rspec 3.5.2 to 3.6.0, and I'm seeing dozens of errors in the output that all look as follows:

```
Could not log "render_template.action_view" event. 
NoMethodError: undefined method `render_views?' for #<Class:0x00000005944120>
[
"/usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:732:in `method_missing'", 
"/usr/local/bundle/gems/rspec-rails-3.6.0/lib/rspec/rails/view_rendering.rb:71:in `render_template'",
"/usr/local/bundle/gems/activesupport-5.1.1/lib/active_support/subscriber.rb:99:in `finish'", 
...
```

Tracing that through, I can see a call to the `render_views?` method is happening on my example group at https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/view_rendering.rb#L65-L74

Is there any clear reason why I would be expected to have this method defined? I feel that maybe this is an upgrade issue, perhaps I need to include `ViewRendering` in the RSpec config? Probably directly related to something in our codebase, but after a few hours, thought I should raise it here in case it does rub against an upgrade path issue.

**Comment by JonRowe** [comment]
Sounds like a duplicate of #1800 especially as this is also coming from the logger.

**Comment by phantomwhale** [comment]
I swear I scanned the issue list before raising this...

Ah yeah, that does indeed seem to be the same issue - will move my attention over there.

Thanks Jon
