### ISSUE TITLE
undefined method `_compute_redirect_to_location' with Rails 4.1.0.beta1

### ISSUE THREAD

**Issue by dnagir** [rspec/rspec-rails#916]
The spec started to fail after updating Rails from 4.0 to 4.1.beta and rspec-rails from 2.14 to 2.14.1:

``` ruby
# spec/requests/invitations_spec.rb
require "spec_helper"

describe "invitations redirect routes" do
  it "should redirect from the old devise_invitable accept link" do
    get("/users/invitation/accept?invitation_token=foo").should redirect_to "/user_invitations/foo/edit"
  end
end
```

The error is:

```
> bundle exec rspec --backtrace spec/requests/invitations_spec.rb
DEPRECATION WARNING: The cattr_* method definitions have been moved into active_support/core_ext/module/attribute_accessors. Please require that instead. (called from require at /Users/dnagir/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72)
DEPRECATION WARNING: devise :token_authenticatable is deprecated. Please check Devise 3.1 release notes for more information on how to upgrade. (called from <class:User> at /Users/dnagir/proj/pc/app/models/user.rb:4)
Current rand time zone: (GMT-04:00) Atlantic Time (Canada). Repro: Time.zone = "Atlantic Time (Canada)"                                                                                                                      |  ETA: ??:??:?? 
  1) invitations redirect routes should redirect from the old devise_invitable accept link
     Failure/Error: get("/users/invitation/accept?invitation_token=foo").should redirect_to "/user_invitations/foo/edit"
     NoMethodError:
       undefined method `_compute_redirect_to_location' for nil:NilClass
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.1.0.beta1/lib/action_dispatch/testing/assertions/response.rb:76:in `normalize_argument_to_redirection'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.1.0.beta1/lib/action_dispatch/testing/assertions/response.rb:59:in `assert_redirected_to'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-expectations-2.14.4/lib/rspec/matchers/built_in/base_matcher.rb:31:in `match_unless_raises'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-expectations-2.14.4/lib/rspec/expectations/handler.rb:24:in `handle_matcher'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-expectations-2.14.4/lib/rspec/expectations/syntax.rb:53:in `should'
     # ./spec/requests/invitations_spec.rb:5:in `block (2 levels) in <top (required)>'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:114:in `block in run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:179:in `call'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:179:in `run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:247:in `instance_eval_with_args'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:106:in `block (2 levels) in run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:108:in `call'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:108:in `run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:446:in `run_hook'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:340:in `run_around_each_hooks'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:256:in `with_around_each_hooks'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:111:in `run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `map'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:371:in `run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
     # /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'

 1/1 |======================================================================================================== 100 =========================================================================================================>| Time: 00:00:01 

Finished in 1.48 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/requests/invitations_spec.rb:4 # invitations redirect routes should redirect from the old devise_invitable accept link

Randomized with seed 61305
```
