### ISSUE TITLE
Undefined method `match' for #<Mime::Type:0x...>

### ISSUE THREAD

**Issue by jensb** [rspec/rspec-rails#572]
Hello,

in my routes I have

```
resources :internal_messages, :except => [:edit, :update] do
  get :reply, :on => :member
end
```

the spec looks like

```
it "route for update should point to route_not_found" do
  { :put => "/users/82/internal_messages/22" }.should_not be_routable
end
it "route for edit should point to route_not_found" do
  { :get => "/users/82/internal_messages/22/edit" }.should_not be_routable
end
```

With Rails 3.0.4 and rspec 2.6 on OS X 10.7.4, this worked. With Rails 3.0.14 and either rspec 2.6 or 2.10.1, this does not work any more. I get 

```
   undefined method `match' for #<Mime::Type:0x104153f60>
```

I also tried replacing "should_Not be_routable" with "should route_to(:controller => .., :action => "route_not_found")" (my default 404 route), which also used to work with Rails 3.0.4. Same result.

Any ideas why?

Thank you!
