### ISSUE TITLE
Failures when using an alternate mock framework

### ISSUE THREAD

**Issue by jeffse** [rspec/rspec-rails#2822]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.3.3
Rails version: 7.1.4.2
RSpec version: 3.13

## Observed behavior

I use Mocha for mocks with RSpec. In my spec_helper.rb file, I have
```ruby
RSpec.configure do |config|
  config.mock_with :mocha
end
```
Using rspec-rails 7.1.0, whenever I run a spec that uses `have_enqueued_job`, I get the following error:
```
     NoMethodError:
       undefined method `configuration' for module RSpec::Mocks
```
This was introduced in https://github.com/rspec/rspec-rails/commit/2f519d426243f0d2d52bf8df5c3cd18bdb65329e. The issue is not present in rspec-rails 7.0.2.

**Comment by JonRowe** [comment]
:wave: Can you give #2823 a spin to see if that fixes your issue?

**Comment by JonRowe** [comment]
A slightly different fix has been released as 7.1.1 but should still work for you
