### ISSUE TITLE
Speculative capybara loading causes unexpected errors

### ISSUE THREAD

**Issue by urbanautomaton** [rspec/rspec-rails#716]
Hi,

After upgrading rspec-rails from 2.11.0 to 2.13.0, I started getting errors out of a controller spec like the following (abridged):

``` ruby
require 'spec_helper'

describe PagesController do
  let(:page) { mock_model(Page) }

  describe "GET 'show'" do
    it "should be successful" do
      Page.stubs(:find => page)
      get "show", :id => page.id
      response.should be_success
    end
  end
end
```

```
$ rspec spec/controllers/pages_controller_spec.rb
F

Failures

  1) PagesController GET 'show' should be successful
     Failure/Error: Page.stubs(:find).with(page.id.to_s).returns(page)
     NoMethodError:
       undefined method `id' for #<Capybara::Session>
     # ./spec/controllers/pages_controller_spec.rb:4
```

It seems that this is because capybara (which we use for our cukes, but not our specs) is now being [speculatively loaded](https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/vendor/capybara.rb#L1-L9) by rspec-rails, and automatically included in controller specs if found. As `#page` is part of capybara's DSL, we get the error above.

I can bodge around it for the moment by naming my memoized `page` something else, but it's a bit frustrating having to avoid collisions with an optional DSL I'm not actually using. Because of the require-and-rescue trick, however, the only way to prevent capybara from loading now is complete uninstallation, which isn't possible because we need capybara for other reasons.

Would you consider a PR that removed the speculative loading, meaning that rspec-rails would only configure capybara if the user had loaded it themselves? This has the potential to break other users' spec suites in potentially surprising ways, though - an alternative might be to wrap the capybara auto-integration in an option, so curmudgeons like me can disable it. What do you think?

Cheers,
Simon
