### ISSUE TITLE
Failing rspec test when using stub_template with Rails 6.1

### ISSUE THREAD

**Issue by glennakamura** [rspec/rspec-rails#2485]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.0.0
Rails version: 6.1.3
RSpec version: 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.2
  - rspec-rails 5.0.0
  - rspec-support 3.10.2

## Observed behaviour

Tests using a previously stubbed template fail if another test clears the view cache.

```
$ bundle exec rspec
..F

Failures:

  1) stub.html.erb renders stub again
     Failure/Error: render
     
     ActionView::Template::Error:
       undefined method `__stub_html_erb___2739773391792524586_14880' for #<ActionView::Base:0x00000000007620>
     # ./spec/views/stub.html.erb_spec.rb:21:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `__stub_html_erb___2739773391792524586_14880' for #<ActionView::Base:0x00000000007620>
     #   ./spec/views/stub.html.erb_spec.rb:21:in `block (2 levels) in <top (required)>'

Finished in 0.05772 seconds (files took 0.69206 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/views/stub.html.erb_spec.rb:20 # stub.html.erb renders stub again
```

## Expected behaviour

All tests pass. (works with Rails 6.0)

## Can you provide an example app?

Example app: https://github.com/glennakamura/rspec_stub_template_failure.git
Expect `bundle exec rspec` to pass but fails with Rails 6.1

**Comment by glennakamura** [comment]
Previously in Rails 6.0, `ActionView::FixtureResolver` did not cache templates but in Rails 6.1 the implementation was refactored to reuse more of `ActionView::OptimizedFileSystemResolver` which enabled caching.  Rspec caches it own `ActionView::FixtureResolver` objects but the `clear_cache` method doesn't get called along with the other resolvers when the view cache is cleared using `ActionView::LookupContext::DetailsKey.clear`.  All of the view context objects containing the compiled methods are cleared but rspec now returns stale stub_template objects cached by `ActionView::FixtureResolver`.

```
      # ActionView::LookupContext::DetailsKey.clear
      def self.clear
        ActionView::ViewPaths.all_view_paths.each do |path_set|
          path_set.each(&:clear_cache)
        end
        ActionView::LookupContext.fallbacks.each(&:clear_cache)
        @view_context_class = nil
        @details_keys.clear
        @digest_cache.clear
      end
```

The commit in rails actionview that changes `ActionView::FixtureResolver` behavior:
https://github.com/rails/rails/commit/c3c1c32f4b3a2505cf78933251dc94dd9f10168a#diff-d61cbf6aceb30d4858710c3b091dff28d6aac3732af8c73ca6e58de51f2c68bf

**Comment by glennakamura** [comment]
FYI, I'm using the following workaround to get tests to pass until a proper fix is released:
```
RSpec.configure do |config|
  config.before :context, type: :view do
    RSpec::Rails::ViewExampleGroup::StubResolverCache
      .instance_variable_get(:@resolvers)
      &.each_value(&:clear_cache)
  end
end
```

**Comment by benoittgt** [comment]
Thanks a lot @glennakamura for the detailed report. Would you like to make a patch?

I think we should clear cache in the after hook. https://github.com/rspec/rspec-rails/blob/53604f4f98d54c95fa88bb1e972229c29e9353f9/lib/rspec/rails/example/view_example_group.rb#L205

**Comment by JonRowe** [comment]
Closing as Rails 6.1 is now out of support, but if someone re-encounters this issue on an in-support version please comment and I'll reopen
