### ISSUE TITLE
Request specs fail after upgrading to Rack 3

### ISSUE THREAD

**Issue by cjamison** [rspec/rspec-rails#2814]
We have a number of request specs for our API and after upgrading Rack from 2.x to 3.x, they all started failing with:
```
     Failure/Error: get "/api/v1/products/1", headers: @headers
     
     NoMethodError:
       undefined method `read' for nil:NilClass
```

The way to resolve these errors is to convert the get request to
```
get "/api/v1/products/1", headers: @headers, env: { 'rack.input' => StringIO.new }
```

However, it seems very verbose to add this to each request. Am I missing an easier / better way to avoid this error?

This is on rspec-rails 7.1.0 and rspec-core 3.13.2.

**Comment by JonRowe** [comment]
:wave: We don't include any behaviour for this ourselves and rely on the upstream Rails / rack-test helpers, is Rack 3 supported by Rails 8? I think 7 is still pinned to 2.x isn't it?

**Comment by cjamison** [comment]
No, Rails 7 is not pinned to 2.x. At least 7.1 is not which is what we are using. 

I see what happened on our end. We have another gem using/requiring Sinatra and at least Sinatra 4.1.1 is requiring rack >= 3.0.0. So, that is what caused our jump. I will see if we want to continue as things are or downgrade Sinatra to something not requiring rack 3.

**Comment by JonRowe** [comment]
My mistake 7.0 is, but not anything later, what version of Rack are you on? It seems like 3.1 made "rack.input" fully optional?

**Comment by cjamison** [comment]
Bundle installed rack 3.1.8. In spite of "rack.input" being optional in this version, it still gave me the error message without me adding it into the test.

**Comment by bradgessler** [comment]
I'm running into similar issues; the request object isn't put into play.

```
terminalwire/server [main] → be rspec spec/requests/bash/installations_spec.rb
FF

Failures:

  1) Bash::Installations GET /index returns a successful response for terminalwire.sh root
     Failure/Error: request.format = :bash if request.user_agent.start_with? "curl" and not request.format.html?

     NoMethodError:
       undefined method `start_with?' for nil
     # ./app/controllers/application_controller.rb:13:in `assign_bash_format'
     # ./spec/requests/bash/installations_spec.rb:6:in `block (3 levels) in <top (required)>'

  2) Bash::Installations GET /index returns bash file contents
     Failure/Error: request.format = :bash if request.user_agent.start_with? "curl" and not request.format.html?

     NoMethodError:
       undefined method `start_with?' for nil
     # ./app/controllers/application_controller.rb:13:in `assign_bash_format'
     # ./spec/requests/bash/installations_spec.rb:6:in `block (3 levels) in <top (required)>'

Finished in 0.1009 seconds (files took 1.78 seconds to load)
2 examples, 2 failures
```

The specs:

```ruby
require 'rails_helper'

RSpec.describe "Bash::Installations", type: :request do
  describe "GET /index" do
    before do
      get "/", headers: { "Host" => "terminalwire.sh" }
    end
    it "returns a successful response for terminalwire.sh root" do
      expect(response).to be_successful
      expect(response.body).to include("Detect operating system")
    end
    it "returns bash file contents" do
      expect(response.body).to include("Detect operating system")
    end
  end
end
```

**Comment by benoittgt** [comment]
Is it possible to get a minimal reproduction code ?

**Comment by hammadxcm** [comment]
I investigated this issue and here's what I found:

**Root Cause:** Rack 3 changed `Rack::MockRequest.env_for` to no longer provide a default `rack.input = StringIO.new("")` when no input is explicitly provided. In Rack 2, this was always set automatically. For GET requests (and any request without a body), `rack.input` ends up as `nil` because rack-test only sets `:input` for non-GET requests with params, and Rack 3 skips setting `rack.input` when `:input` is nil.

**Already fixed upstream:** Rails (both 7.1.5.2 and 8.0.2) patched `Request#raw_post` / `read_body_stream` to guard against nil `rack.input`:

```ruby
# actionpack - action_dispatch/http/request.rb
def read_body_stream
  if body_stream  # guards against nil rack.input
    reset_stream(body_stream) { ... }
  end
end
```

**Still affected:** Application code or middleware that directly accesses `request.body.read` or `env['rack.input'].read` without nil-checking will still fail. That's what the reporters here are hitting.

**Why this isn't an rspec-rails issue:** `RequestExampleGroup` is a thin wrapper — it just includes `ActionDispatch::IntegrationTest::Behavior` and delegates everything to Rails. It doesn't touch the request env. Notably, Rails' own controller `test_case` explicitly sets `env["rack.input"] = StringIO.new` in its `scrub_env!` method, but the integration test path (used by request specs) does not.

**Where the proper fix belongs:** rack-test (should set a default `input: ""` for all requests) or Rails' `ActionDispatch::Integration::Session#process` (should ensure `rack.input` is always present, matching controller test behavior).

**Workaround:** Users on affected versions can add `env: { 'rack.input' => StringIO.new }` to individual requests, or add a global before hook:

```ruby
# spec/support/rack_input.rb or spec/rails_helper.rb
RSpec.configure do |config|
  config.before(:each, type: :request) do
    integration_session.instance_variable_get(:@app) # ensure session exists
  end
end
```

Or more directly, patch it in a shared context if the error persists across many specs.

Updating to Rails 7.1.5.2+ / 8.0.2+ should resolve the `raw_post` variant of this error. Remaining failures point to app-level code that should be updated to handle nil `rack.input` (which is valid per the Rack 3 SPEC).
