### PR TITLE
Fix support for Rails 4.2

### LINKED ISSUE #2477: RSpec 4.1 breaks on Rails 4.2
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.4.10
Rails version: 4.2.11.3
RSpec version: 4.1.0

## Observed behaviour

RSpec 4.1 does not work start on Rails 4.2.11.3, while 4.0 does

```
     Failure/Error: example.run
     
     NameError:
       undefined local variable or method `use_transactional_tests' for #<RSpec::ExampleGroups::Welcome::Index:0x00007fcb64cdbf40>
       Did you mean?  use_transactional_fixtures
```

Tracked down with `git bisect` down to 073daad07027d7fb53a3f7ac3b06a0dd4af498da

## Expected behaviour

Keeps working with Rails 4.1 or `gemspec` specifies `>= 5.0` to prevent update to 4.1

https://github.com/rspec/rspec-rails/blob/main/rspec-rails.gemspec#L36

## Can you provide an example app?

Travis CI failure: https://travis-ci.org/github/diowa/ruby2-rails4-bootstrap-heroku/builds/761888443

### PR DESCRIPTION
**Pull request by tagliala**
Rails 4.2 does not have `use_transactional_tests` defined

Fix #2477

Supersedes #2479 (I was using a wrong branch)

### CODE REVIEW

File: lib/rspec/rails/fixture_support.rb [hunk 1]
```diff
@@ -12,8 +12,14 @@ module FixtureSupport
         # @private prevent ActiveSupport::TestFixtures to start a DB transaction.
         # Monkey patched to avoid collisions with 'let(:name)' in Rails 6.1 and after
         # and let(:method_name) before Rails 6.1.
-        def run_in_transaction?
-          use_transactional_tests && !self.class.uses_transaction?(self)
+        if ::Rails::VERSION::STRING > '5'
```
Comment (tagliala) [inline lib/rspec/rails/fixture_support.rb:15]: This check is inspired by 

https://github.com/rspec/rspec-rails/blob/c100cf1c26bc4f20f54900f22b360b6c2d0553a8/lib/rspec/rails/fixture_support.rb#L24

**Review by pirj — APPROVED** [review]
Looks good, thank you!
Please add a Changelog record.

**Comment by tagliala** [comment]
Is the failure `RSpec CI / Ruby: 2.6.6, Rails: ~> 5.1.0 (pull_request) ` expected?

**Comment by pirj** [comment]
Thank you!

**Comment by JonRowe** [comment]
Thanks, this will be released later today as 4.1.2. 

(Please note future travellers, this does not mean we are supporting Rails 4.2 on this series of RSpec, this was an exception to the rule 😃 )
