### PR TITLE
Ensure mocks config available

### LINKED ISSUE #2822: Failures when using an alternate mock framework
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.3.3
Rails version: 7.1.4.2
RSpec version: 3.13

## Observed behavior

I use Mocha for mocks with RSpec. In my spec_helper.rb file, I have
```ruby
RSpec.configure do |config|
  config.mock_with :mocha
end
```
Using rspec-rails 7.1.0, whenever I run a spec that uses `have_enqueued_job`, I get the following error:
```
     NoMethodError:
       undefined method `configuration' for module RSpec::Mocks
```
This was introduced in https://github.com/rspec/rspec-rails/commit/2f519d426243f0d2d52bf8df5c3cd18bdb65329e. The issue is not present in rspec-rails 7.0.2.

### PR DESCRIPTION
**Pull request by JonRowe**
Should fix #2822

### CODE REVIEW

File: lib/rspec/rails/matchers/active_job.rb [hunk 1]
```diff
@@ -1,5 +1,6 @@
 require "active_job/base"
 require "active_job/arguments"
```
Comment (pirj) [inline lib/rspec/rails/matchers/active_job.rb:2]: We check if mocks are defined [here](https://github.com/rspec/rspec-rails/blob/609bb83a76c11c67076ff2619fd5f47edd6325ce/lib/rspec/rails/active_record.rb#L10). Should we do the same here instead of requiring what’s not used?

Comment (JonRowe) [reply lib/rspec/rails/matchers/active_job.rb:2]: The difference is here we are actually using it

Comment (pirj) [reply lib/rspec/rails/matchers/active_job.rb:2]: We’re only using it if verified partial doubles are checked, right? Which is not the case when RSpec is configured to mock with an alternative framework. Or am I missing something? It looks like before #2808 everything worked just fine, but apparently rspec-mocks were not required and RSpec::Mocks was not defined, and no problem.

**Comment by jeffse** [comment]
@JonRowe Yes, this works for me!

File: lib/rspec/rails/matchers/active_job.rb (hunk 1 above)
Comment (JonRowe) [reply lib/rspec/rails/matchers/active_job.rb:2]: We don't want to skip the check just because someone is using another mocking framework

Comment (pirj) [reply lib/rspec/rails/matchers/active_job.rb:2]: If someone is using another framework, the result of the check will always be false. So it’s not that we skip it, we shortcut it.
