### ISSUE TITLE
All specs failing in 2.6.0

### ISSUE THREAD

**Issue by kerryb** [rspec/rspec-rails#368]
I'm sure this is something stupid I've done, but after upgrading rspec-\* from 2.5.0 to 2.6.0 all my specs fail with the following stack trace:

```
 Failure/Error: Unable to find matching line from backtrace
 undefined method `metadata' for nil:NilClass
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/activesupport-3.0.7/lib/active_support/whiny_nil.rb:48:in `method_missing'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/capybara-0.4.1.2/lib/capybara/rspec.rb:7:in `block (2 levels) in <top (required)>'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:324:in `instance_eval'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:324:in `instance_eval_with_rescue'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/hooks.rb:43:in `run_in'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/hooks.rb:79:in `block in run_all'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/hooks.rb:79:in `each'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/hooks.rb:79:in `run_all'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/hooks.rb:125:in `run_hook_filtered'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:226:in `eval_after_eachs'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example.rb:149:in `run_after_each'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example.rb:54:in `block in run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example.rb:107:in `with_around_hooks'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example.rb:45:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:294:in `block in run_examples'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:290:in `map'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:290:in `run_examples'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:262:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `block in run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `map'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `block in run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `map'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `block in run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `map'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/example_group.rb:263:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/command_line.rb:24:in `block (2 levels) in run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/command_line.rb:24:in `map'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/command_line.rb:24:in `block in run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/reporter.rb:12:in `report'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/command_line.rb:21:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/runner.rb:80:in `run_in_process'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/runner.rb:69:in `run'
 # /Users/kerry/.rvm/gems/ruby-1.9.2-p180@portico/gems/rspec-core-2.6.0/lib/rspec/core/runner.rb:11:in `block in autorun'
```

Project is using Rails 3.0.7.
