### ISSUE TITLE
undefined method `env' for nil:NilClass in RSpec 2.10

### ISSUE THREAD

**Issue by sekrett** [rspec/rspec-rails#534]
Hello!

After upgrading to 2.10 in my Rails 3.2 application I get lots of errors:

<pre>1) PagesController as admin user new action should render new template
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `env' for nil:NilClass
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/devise-2.0.4/lib/devise/test_helpers.rb:33:in `warden'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-rails-2.10.0/lib/rspec/rails/adapters.rb:15:in `block (2 levels) in setup'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example.rb:178:in `instance_eval'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example.rb:178:in `instance_eval'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/hooks.rb:23:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/hooks.rb:63:in `block in run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/hooks.rb:63:in `each'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/hooks.rb:63:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/hooks.rb:400:in `run_hook'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:298:in `run_before_each_hooks'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example.rb:239:in `run_before_each'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example.rb:86:in `block in run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example.rb:195:in `with_around_each_hooks'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example.rb:84:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:353:in `block in run_examples'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:349:in `map'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:349:in `run_examples'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:335:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:336:in `block in run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:336:in `map'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/example_group.rb:336:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/reporter.rb:34:in `report'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/runner.rb:69:in `run'
     # /Users/sekrett/.rvm/gems/ruby-1.9.3-p125-perf/gems/rspec-core-2.10.0/lib/rspec/core/runner.rb:10:in `block in autorun'</pre>

Probably it is related to Devise, since this error I see only for controllers. It never happened before. I can try to write a minimal application to reproduce the bug if needed.
For now I downgraded to 2.9 to make it work.
