### ISSUE TITLE
undefined method `configure' when running rake spec:rcov

### ISSUE THREAD

**Issue by kerryb** [rspec/rspec-rails#236]
After upgrading from 2.0.0.rc to 2.0.0, `rake spec:rcov` no longer works on my Rails 3 project. I see the following stack trace:

```
/Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/rspec-rails-2.0.0/lib/rspec/rails.rb:11: undefined method `configure' for RSpec:Module (NoMethodError)
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:227:in `load_dependency'
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
  from /Users/kerry/work/vdc/portico/spec/spec_helper.rb:4
  from ./spec/controllers/application_controller_spec.rb:1:in `require'
  from ./spec/controllers/application_controller_spec.rb:1
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/rcov-0.9.9/bin/rcov:516:in `load'
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/gems/rcov-0.9.9/bin/rcov:516
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/bin/rcov:19:in `load'
  from /Users/kerry/.rvm/gems/ruby-1.8.7-p302@portico/ruby/1.8/bin/rcov:19
```

Here is my Gemfile:

```
source "http://rubygems.org"

gem "rails", "3.0.0"

gem "crowd"
gem "formtastic"
gem "flutie"
gem "pg"

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem "autotest"
  gem "autotest-growl"
  gem "capybara"
  gem "cucumber-rails", "0.3.2"
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "factory_girl_generator"
  gem "launchy"
  gem "rcov"
  gem "rspec-rails"
  gem "spork"
  gem "shoulda"
  gem "webmock", :require => nil
  gem "wirble"
end
```
